-- AlterTable
ALTER TABLE `Organisation_User_position` MODIFY `user_position` ENUM('FULL_STACK_DEVELOPER', 'POWER_BI_DEVELOPER', 'SALES', 'HUMAN_RESOURCE', 'TESTING', 'SALESFORCE', 'PUBLIC', 'CUSTOMER_SUCCESS') NOT NULL;

-- AlterTable
ALTER TABLE `tags` MODIFY `user_position` ENUM('FULL_STACK_DEVELOPER', 'POWER_BI_DEVELOPER', 'SALES', 'HUMAN_RESOURCE', 'TESTING', 'SALESFORCE', 'PUBLIC', 'CUSTOMER_SUCCESS') NOT NULL;
